name: JSON Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install jsonlint
      run: pip install jsonlint-cli

    - name: Lint JSON Files
      run: |
        find . -name '*.json' -type f -print0 | xargs -0 jsonlint -q

    - name: Run Python Script
      run: |
        python -m pip install --upgrade pip
        python JsonValidation/run.py
