name: JSON Validator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install json5
        run: pip install json5

      - name: Lint JSON Files
        run: |
          find . -name '*.json' -type f -exec sh -c 'python -m json.tool {} >&2' \;

      - name: Validate Json Syntax
        run: |
          python -m pip install --upgrade pip
          python -c "from ValidationInitializer import ValidationInitializer; v = ValidationInitializer(); v.run_json_syntax_validator();"

      - name: Validate Json Structure
        run: |
          python -m pip install --upgrade pip
          python -c "from ValidationInitializer import ValidationInitializer; v = ValidationInitializer(); v.run_json_structure_validator()"
