name: JSON Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Lint JSON Files
        run: |
          find . -name '*.json' -type f -exec jq empty {} \;

      - name: Run Python Script
        run: |
          python -m pip install --upgrade pip
          python JsonValidation/run.py